server:
  port: 8080

spring:
  profiles:
    active: dev #默认为开发环境
  freemarker:
    request-context-attribute: request
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml



swagger:
  enabled: true #是否开启swagger文档功能