spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nana?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

logging:
  level:
      root: info #日志级别，级别包括：TRACE、DEBUG、INFO、WARN 和 ERROR，定义于 ch.qos.logback.classic.Level类
      com.zhuxl.cc.nana.dao: debug
      com.zhuxl.cc.nana.component: debug
