server:
  port: 8080

spring:
  profiles:
    active: dev #默认为开发环境
  freemarker:
    request-context-attribute: request

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml



swagger:
  enabled: true #是否开启swagger文档功能