server:
  port: 8080

spring:
  profiles:
    active: dev #默认为开发环境
  freemarker:
    request-context-attribute: request
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  aop:
    auto: true #Add @EnableAspectJAutoProxy.
    proxy-target-class: false #Whether subclass-based (CGLIB) proxies are to be created (true), as opposed to standard Java interface-based proxies (false).

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml



swagger:
  enabled: true #是否开启swagger文档功能
